### ISSUE TITLE
What about when the image has been cached by the browser?

### ISSUE THREAD

**Issue by navigatr** [toddmotto/echo#105]
What about when the image has been cached by the browser? Will it bypass this and fetch it again from the server?

**Comment by osopolar** [comment]
The Firefox web developer tools (network tab) shows the response status code of all requests. If I load the site with empty caches I get status 200 (OK). If I reload the page, without clearing cache, I get 304 (Not Modified). So it seems browser caching is still working.

**Comment by toddmotto** [comment]
Sweet, thanks @osopolar for testing. Closing off.
