### ISSUE TITLE
lazy load on click as opposed to scroll

### ISSUE THREAD

**Issue by Pau1fitz** [toddmotto/echo#110]
Todd, as usual great work, and love that you have explained all the code.

Just wanted to know if you knew of any way of loading the images on a click, rather than a scroll. A bit like the first time you click load more on Instagram. so at the end of the initial set of images loaded there would be a load more button, which lets say would load another set of images, which would then have the load more button below this again.

I hope this makes sense. If not let me know and I can provide more info.

As always thanks for your help and guidance.

Thanks, Paul

**Comment by crispen-smith** [comment]
Isn't this more like infinite scroll than lazy loading?

**Comment by Pau1fitz** [comment]
@crispen-smith ah gotcha! cheers for that guidance!
