### ISSUE TITLE
use echo,jquery appear bug

### ISSUE THREAD

**Issue by cdefg198** [toddmotto/echo#111]
import:
`<script src="/Scripts/jquery-1.10.2.min.js"></script>
<script src="/Scripts/echo.min.js"></script>`

use eg:
`$.getScript("/Scripts/bootstrap.min.js").done(function(script, textStatus,jqxhr) {    
   console.log(jqxhr.status);
})
.fail(function(jqxhr, settings, exception ) {
   console.log(jqxhr.status);
});`
Uncaught TypeError: Cannot read property 'done' of undefined(…)

**Comment by toddmotto** [comment]
This isn't anything to do with echo.js, `getScript()` is the undefined property.
