### ISSUE TITLE
Using echo.js with Angular.js

### ISSUE THREAD

**Issue by manaberg** [toddmotto/echo#62]
```
<img src="css/img/preloader.gif" alt data-echo="{{item.image}}">
```

I want to output a javascript object property which points to an img to be loaded by echo.js data-echo but it is failing. I am not exprienced enough to understand how to output the actual string instead of the javascript expression.

Is there any direction you could point me to in order to make this work with angular? I would appreciate it because I like the library a lot.

Thanks for your time.

**Comment by waltercolindres** [comment]
Having an issue. I see the image load into the url, but not the view.

**Comment by waltercolindres** [comment]
Using AngularJS v1.3.8

Images not loading. Tried a static url and a dynamic version. I can see the image come in on the dom, but it is not loading into the view.

**Comment by junerockwell** [comment]
Has anyone figured out how to make this work with AngularJS?

**Comment by stramel** [comment]
@waltercolindres Did you ever resolve this?

**Comment by waltercolindres** [comment]
@stramel No. Never did. :(
