### ISSUE TITLE
data-echo-background?

### ISSUE THREAD

**Issue by renege** [toddmotto/echo#70]
How to do the data-echo-background? I'm at version 1.6.0.
```
<style>
div{ background: url('/bg/1pixel.gif') center center no-repeat; height: 300px; width: 100%; } 
</style>
 <div data-echo-background="/bg/photo.jpg">foobar</div>
```
Does not work. Still shows the 1pixel image.
All my <img>'s are working.

**Comment by renege** [comment]
// cc @jonathan-fielding

**Comment by feitla** [comment]
bower version 1.7 isn't including @ingramos's update the data-echo-background to remove the attribute on unload 
1118a8184727044d89b070f96d368e44c6c75f8d

**Comment by jonathan-fielding** [comment]
Ok will look at doing another release

**Comment by jonathan-fielding** [comment]
ok that is now is 1.7.1 which i just pushed out, thanks
